### PR TITLE
fix/issues/57-58 Cannot define an uncentralized images

### LINKED ISSUE #57: Cannot define an uncentralized FileImage
**Maroto version:**
Latest

**I'm submitting a ...** 

- [x] bug report
- [ ] feature request

**Current behavior:**
There is no implementation of uncentralized FileImage.

**Expected behavior:**
We should have uncentralized FileImage.

**Steps to reproduce:**
If you pass a *prop* forcing uncentralized , it will centralize the barcode anyway.

**Related code:**
https://github.com/johnfercher/maroto/blob/51bcd1b9a20143cb70ccb295151d863854b93f79/pkg/pdf/pdf.go#L300-L304

### LINKED ISSUE #58: Cannot define an uncentralized Base64Image
**Maroto version:**
Latest

**I'm submitting a ...** 

- [x] bug report
- [ ] feature request

**Current behavior:**
There is no implementation of uncentralized Base64Image.

**Expected behavior:**
We should have uncentralized Base64Image.

**Steps to reproduce:**
If you pass a *prop* forcing uncentralized , it will centralize the barcode anyway.

**Related code:**
https://github.com/johnfercher/maroto/blob/51bcd1b9a20143cb70ccb295151d863854b93f79/pkg/pdf/pdf.go#L320-L324

### PR DESCRIPTION
**Pull request by SuddenGunter**
**Description**
- Gopkg.lock was committed accidently, will undo it in different branch and recreate PR. This is just a draft
- This PR allows to define uncentralized FileImage (and base64Image also cause they share same API. Also I suppose barcode centralization can be resolved later with this code also). 
- main.go included only for demo purposes so you can test it locally
- It mostly works, see code in main.go and generated PDF:
1571082952_2255_14102019_315x880
I'm satisfied with left alignment, but top (y position) makes me worry a little bit. From what I see - it moves out of a row. Is this the correct behaviour or image must not move out of row?
What should I do then if for example image height is 50px, row size is 100 px and user suggest to position image with top alignment 55px (so 5px is out of image). Crop it? Stick it to the bottom of the row?

I haven't added any unit tests and didn't update any docs because it's just a draft of my proposal
 
**Related Issue**
resolve #57 
resolve #58 

**Checklist**

- [x] All methods associated with structs has ```func (s *struct) method() {}``` name style. 
- [x] Wrote unit tests for new/changed features. 
- [x] Updated docs/doc.go 
- [x] Updated pkg/pdf/example_test.go 
- [x] Updated README.md 
- [x] New public methods has comments upside them explaining what it does

### CODE REVIEW

**Comment by johnfercher** [comment]
Nice work 👍, I will have a look. But, it shouldn't add a new page in this case.

**Comment by johnfercher** [comment]
Hey, I checkout your code and found something. For every new **row** added, is computed the sum of all **rows** height, when this sum pass the PDF page height, is added a new page. And then the height become 0.0. So, in this case was added a new page correctly.

The issue that the image is far down from the upper limit of the PDF is because you're passing the **top** value of 111. This **top** is always relative to the current **row**, so you should always pass a value less than **row** height.

**Comment by johnfercher** [comment]
Dude, I think this issue is done. Congrats :D

About the possibility to set a **top** and put the image out of the **row** area, I think we could create another issue and relates to this one.

**Comment by SuddenGunter** [comment]
Thanks for the review

Will fix checklist and add tests later tonight and update a PR

**Comment by SuddenGunter** [comment]
1  Updated pkg/pdf/example_test.go 
 - do not need, already has sample for fileImage
2  Updated docs/doc.go 
What should I add?
There were no samples related to image
3  Updated README.md 
 - do not need, already has sample for fileImage

**Comment by SuddenGunter** [comment]
Also I'm not really sure what to do here:
https://github.com/johnfercher/maroto/blob/69cf736a06f9d66d3a06303608591b6197302e7d/internal/mocks/math.go#L65

**Comment by johnfercher** [comment]
The checklist is fine. About this mock, you should run the [golang mockery](https://github.com/vektra/mockery) to the Math interface. It will create this method for you. Another thing is that [this code](https://codecov.io/gh/johnfercher/maroto/compare/4e1ed9a5ead56a2d0e0337fbf91cdedc5eaac136...69cf736a06f9d66d3a06303608591b6197302e7d/src/internal/image.go) doesn't have unit tests.

**Comment by SuddenGunter** [comment]
ok
mock created, tests almost ready
fighting windmills at the moment: some magic happens in tests:
`https://travis-ci.com/johnfercher/maroto/builds/132225634` - but I've just copypasted your test with 2 params changed.

**Comment by SuddenGunter** [comment]
fixed

**Comment by johnfercher** [comment]
We need to change the type to int because testify cannot assert the method assertion with floats, lol.

**Pull request merged**
