### PR TITLE
feature/59-allow-uncentralized-barcode-and-qrcode 

### LINKED ISSUE #59: Cannot define an uncentralized Barcode
**Maroto version:**
Latest

**I'm submitting a ...** 

- [x] bug report
- [ ] feature request

**Current behavior:**
There is no implementation of uncentralized Barcode.

**Expected behavior:**
We should have uncentralized Barcode.

**Steps to reproduce:**
If you pass a *prop* forcing uncentralized , it will centralize the barcode anyway.

**Related code:**
https://github.com/johnfercher/maroto/blob/51bcd1b9a20143cb70ccb295151d863854b93f79/pkg/pdf/pdf.go#L352-L356

### LINKED ISSUE #60: Cannot define an uncentralized QrCode
**Maroto version:**
Latest

**I'm submitting a ...** 

- [x] bug report
- [ ] feature request

**Current behavior:**
There is no implementation of uncentralized QrCode..

**Expected behavior:**
We should have uncentralized QrCode.

**Steps to reproduce:**
If you pass a *prop* forcing uncentralized, it will centralize the barcode anyway.

**Related code:**
https://github.com/johnfercher/maroto/blob/51bcd1b9a20143cb70ccb295151d863854b93f79/pkg/pdf/pdf.go#L373-L377

### PR DESCRIPTION
**Pull request by SuddenGunter**
**Description**
allows uncentralized barcode/qrcode 
main.go only for testing, will be remove when pr would be ready for review.
Result pdf for current main.go:
1571337654_2140_17102019_343x765
Same main.go on current dev:
1571337775_2142_17102019_288x658

I see 2 related issues: 
- why qr code so blurry?
- why barcode ignores proportion (16x9 vs 4x3)?

**Related Issue**
resolve #59 
resolve #60 

**Checklist**
> check with "x", if applied to your change

- [x] All methods associated with structs has ```func (s *struct) method() {}``` name style. 
- [x] Wrote unit tests for new/changed features. 
- [ ] Updated docs/doc.go 
- [ ] Updated pkg/pdf/example_test.go 
- [ ] Updated README.md 
- [ ] New public methods has comments upside them explaining what it does 
- [ ] Executed `go fmt github.com/johnfercher/maroto/...` to format all files

### CODE REVIEW

**Comment by SuddenGunter** [comment]
```
codecov/patch — 93.34% of diff hit (target 95.67%)
codecov/project — 96.34% (+0.68%) compared to 87d45ab
```
@johnfercher do you have any idea what I've made wrong here?

**Comment by johnfercher** [comment]
* why qr code so blurry?
Strange, I will check later.

* why barcode ignores proportion (16x9 vs 4x3)?
In the master code it works, maybe your modification breaks the feature.

* do you have any idea what I've made wrong here?
The code in the maroto.go Barcode doesn't have unit tests yet, we should add because your modification affect that code. You could follow de QrCode unit test example.

**Comment by SuddenGunter** [comment]
>why barcode ignores proportion (16x9 vs 4x3)?
>In the master code it works, maybe your modification breaks the feature.

I've tested code with dev without my changes - still wasn't working

**Comment by johnfercher** [comment]
I tested my dev and my master, both are working, lol. I will check better later.

**Comment by johnfercher** [comment]
Have you tried different percent values? And there is an constraint in the proportion, how you can see below.

https://github.com/johnfercher/maroto/blob/76210eee05ffeba27b56270d0363ae741093d780/pkg/props/prop.go#L138-L140

**Comment by SuddenGunter** [comment]
@johnfercher I guess I'd broke codecov when rebased branch and squashed some commits. 
Can it happen, what do you think?
https://codecov.io/gh/johnfercher/maroto/compare/b630a80a0ee08a62b5a3047fc809a0e0a29744c3...00476f03195c85c336f7b9c3a86a7ebca6b61eb0

`Missing base report.
Unable to compare commits because the base of the compare did not upload a coverage report.
`
I'll delete this PR I guess and then recreate a new one. Sorry.

**Comment by SuddenGunter** [comment]
@johnfercher pls mark as INVALID

**Pull request closed without merging**
