### PR TITLE
Make top margin be able to be zero. --Issue #192

### PR DESCRIPTION
**Pull request by EddieSCJ**
# Problem

**I can't define top margin as zero**

Issue #192 
 
**To Reproduce**
Code to reproduce the behavior:

```
package main

import (
	"fmt"
	"fruitfulpdf/data"
	"github.com/johnfercher/maroto/pkg/color"
	"github.com/johnfercher/maroto/pkg/consts"
	"github.com/johnfercher/maroto/pkg/pdf"
	"github.com/johnfercher/maroto/pkg/props"
	"os"
)

func main() {
	m := pdf.NewMaroto(consts.Portrait, consts.A4)
	m.SetPageMargins(0, 0, 0)

	buildHeading(m)

	if err := m.OutputFileAndClose("pdfs/fruits.pdf"); err != nil {
		fmt.Println("Couldn't save PDF: ", err)
		os.Exit(1)
	}
	fmt.Println("PDF saved successfully")
}

func buildHeading(m pdf.Maroto) {
	m.SetBackgroundColor(color.Color{
		Red:   3,
		Green: 166,
		Blue:  166,
	})
	m.Row(10, func() {
		m.Col(12, func() {
			m.Text("Products", props.Text{
				Top:    2,
				Size:   13,
				Color:  color.NewWhite(),
				Family: consts.Arial,
				Style:  consts.Bold,
				Align:  consts.Center,
			})
		})
	})
}
```

I just think it's because inside this method it only changes the `s.marginTop` when the top value is greater than ten, so the minimum top margin will EVER be ten and it's not customizable follow the code.

The need to have it greater than ten is because in NewMarotoCustomSize the margin will be ten by default, and in the `SetPageMargins` it will not change at all for the top margin, so we need a `marginTop` in PdfMaroto to make some calculus.

```
// SetPageMargins overrides default margins (10,10,10)
// the new page margin will affect all PDF pages
func (s *PdfMaroto) SetPageMargins(left, top, right float64) {
	if top > 10 {
		s.marginTop = top - 10
	}

	s.Pdf.SetMargins(left, 10.0, right)
}
```

The SetPageMargins was supposed to override the default margins, but it does not override the top margin anyway, but it is calculated in someplace with a sum.

Sometimes, in part of the code as in the method GetPageMargins, the maroto top margin is added to the pdf top margin. 
Idk if it could occur in other pieces of code. 

```
func (s *PdfMaroto) GetPageMargins() (left float64, top float64, right float64, bottom float64) {
	left, top, right, bottom = s.Pdf.GetMargins()
	top += s.marginTop

	return
}
```

**My suggestion is to make have no condition to set the `s.marginTop` value in another method, so we can use this without break the current code**

Something like

```
// SetPageMargins overrides default margins (10,10,10)
// the new page margin will affect all PDF pages
func (s *PdfMaroto) SetPageMargins(left, top, right float64) {
        s.marginTop = top - 10
	s.Pdf.SetMargins(left, 10.0, right)
}

func (s *PdfMaroto) SetTopPageMargin(top float64) {
	s.marginTop = top - 10
}
```

# Solution

Remove >10 conditional, and creating new methods to set margins individually, and use constant to default margin value,

### CODE REVIEW

**Comment by EddieSCJ** [comment]
Issue #192

**Comment by johnferchermeli** [comment]
LGTM :D, we only have to fix those doc issues and write some unit tests.

**Comment by EddieSCJ** [comment]
Hey @johnfercher, I would like to help, if I can do those stuff, just let me know. I will add some unit tests to this PR and read the doc to know how if I can make that changes.

**Comment by EddieSCJ** [comment]
@johnferchermeli @johnfercher I just think it's done, can u review and give me feedback if is there anything you want me to change?

**Comment by EddieSCJ** [comment]
@johnferchermeli @johnfercher hi

**Comment by jeancabral** [comment]
LGTM

**Review by portal7 — APPROVED** [review]
LGTM too

**Comment by johnfercher** [comment]
Hello, I identified an issue with this implementation. Indeed gofpdf allows us to define a 0 margin top, but if you turn on the border drawned by maroto, you will see that the PDF generation starts to acumulate an error in X offset. This is because gofpdf allows you to set the margin 0, but it doesn't apply. I think we cannot merge this PR right now.

Maybe we could fix this issue in gofpdf first and come back here to see if everything are working.

**Pull request closed without merging**
