### PR TITLE
allow uncentralized qr/bar-codes

### LINKED ISSUE #59: Cannot define an uncentralized Barcode
**Maroto version:**
Latest

**I'm submitting a ...** 

- [x] bug report
- [ ] feature request

**Current behavior:**
There is no implementation of uncentralized Barcode.

**Expected behavior:**
We should have uncentralized Barcode.

**Steps to reproduce:**
If you pass a *prop* forcing uncentralized , it will centralize the barcode anyway.

**Related code:**
https://github.com/johnfercher/maroto/blob/51bcd1b9a20143cb70ccb295151d863854b93f79/pkg/pdf/pdf.go#L352-L356

### LINKED ISSUE #60: Cannot define an uncentralized QrCode
**Maroto version:**
Latest

**I'm submitting a ...** 

- [x] bug report
- [ ] feature request

**Current behavior:**
There is no implementation of uncentralized QrCode..

**Expected behavior:**
We should have uncentralized QrCode.

**Steps to reproduce:**
If you pass a *prop* forcing uncentralized, it will centralize the barcode anyway.

**Related code:**
https://github.com/johnfercher/maroto/blob/51bcd1b9a20143cb70ccb295151d863854b93f79/pkg/pdf/pdf.go#L373-L377

### PR DESCRIPTION
**Pull request by SuddenGunter**
**Description**
allows uncentralized barcode/qrcode 
potential fix for codecov issue occured here:
https://github.com/johnfercher/maroto/pull/103 - @johnfercher pls mark as invalid
https://github.com/johnfercher/maroto/pull/94 - @johnfercher pls mark as invalid

**Related Issue**
resolve #59 
resolve #60 

**Checklist**
> check with "x", if applied to your change

- [x] All methods associated with structs has ```func (s *struct) method() {}``` name style. 
- [x] Wrote unit tests for new/changed features. 
- [x] Updated docs/doc.go 
- [x] Updated pkg/pdf/example_test.go 
- [x] Updated README.md 
- [x] New public methods has comments upside them explaining what it does 
- [x] Executed `go fmt github.com/johnfercher/maroto/...` to format all files

### CODE REVIEW

**Comment by SuddenGunter** [comment]
oh, I get it now
it's missing  base report because it's your commit @johnfercher  https://github.com/johnfercher/maroto/commit/b630a80a0ee08a62b5a3047fc809a0e0a29744c3
because it wasn't run through pipeline.
so I cannot understand how to  fix the issue here and if this is an issue at all:
because codecov has problems with trying to measure coverage diff between my code and "missing report".  Project coverage will be increased after my PR merge. 
Isn't this enough?
I mean - we cannot have honest coverage diff measure untill we have some other commit as latest on `dev` - some that has coverage metrics.

**Comment by johnfercher** [comment]
Hi, I will check this issue for you. I just merged the dev into your branch. Could you test the barcode and qrcode positioning with two columns? I found a bug in this case and fixed it in dev branch.

**Comment by SuddenGunter** [comment]
@johnfercher it's working now!
Now I see https://codecov.io/gh/johnfercher/maroto/pull/104/src/pkg/pdf/pdf.go - what lines must be covered

**Comment by SuddenGunter** [comment]
>Could you test the barcode and qrcode positioning with two columns
ok, give me a moment

**Comment by johnfercher** [comment]
Nice, thank you very much =)

**Comment by SuddenGunter** [comment]
1571864597_0003_24102019_1086x434

^ for `
package main

import (
	"github.com/johnfercher/maroto/pkg/consts"
	"github.com/johnfercher/maroto/pkg/pdf"
	"github.com/johnfercher/maroto/pkg/props"
	"github.com/jung-kurt/gofpdf"
	"log"
)

func main() {
	file := pdf.NewMaroto(gofpdf.OrientationPortrait, consts.A4)
	file.Row(90, func() {
		file.Col(func() {
			file.Barcode("img.png", props.Barcode{
				Left:    10,
				Top:     1,
				Center:  false,
				Percent: 100,
				Proportion:props.Proportion{16,9},
			})
		})
		file.Col(func() {
			file.Barcode("img.png", props.Barcode{
				Left:    100,
				Top:     1,
				Center:  false,
				Percent: 30,
				Proportion:props.Proportion{16,9},
			})
		})
	})

	err := file.OutputFileAndClose("demo.pdf")
	if err != nil {
		log.Fatal(err)
	}
}`

**Comment by SuddenGunter** [comment]
don't really like how it looks - I mean from what I see coordinates are being calculated based on row, not column. 
for example we have to columns here and I would expect that when I hit Left=100, Center=fasle in the second column - it would be 100 from second column start, not row start?

**Comment by johnferchermeli** [comment]
I don't get it. The position is calculated using the row a column information, the position should be based on the current column inside the row. So, if you set left to 100 using two columns, it will use the middle of the PDF plus 100.

**Comment by johnferchermeli** [comment]
I tested your branch, the behavior is correct.

This image below has QrCodes and Barcodes not centralized, they are in the left border of the cells.
Captura de Tela 2019-10-23 às 21 05 29

This image below has QrCodes and Barcodes not centralized, they aren't in the left border of the cells, because I set left as 10.
Captura de Tela 2019-10-23 às 21 05 05

**Comment by johnfercher** [comment]
So I will merge it :)

**Pull request merged**
