### PR TITLE
Feature/Expose FPDF `AddUTF8FontFromBytes` method

### PR DESCRIPTION
**Pull request by thijsheijden**
**Description**

This PR is useful because it makes it easier to add custom UTF8 fonts. Loading fonts from a file path is not always possible, and it requires the font files to be copied to the place the binary will be executed, and then to figure out the absolute path to the directory. Think of Kubernetes and serverless deployments. Using `embed` it is now trivially easy to embed fonts in the binary and load them into Maroto.

**Related Issue**

**Checklist**
> check with "x", if applied to your change

- [x] All methods associated with structs has ```func (s *struct) method() {}``` name style. 
- [x] Wrote unit tests for new/changed features. 
- [ ] Updated docs/doc.go 
- [ ] Updated pkg/pdf/example_test.go 
- [x] Updated README.md 
- [ ] Updated all examples inside internal/examples 
- [x] New public methods/structs/interfaces has comments upside them explaining they responsibilities 
- [x] Executed `make dod` with none issues pointed out by `golangci-lint` and `goreportcard-cli`

### CODE REVIEW

**Comment by johnfercher** [comment]
Could you add an example in `Updated pkg/pdf/example_test.go`?

**Comment by thijsheijden** [comment]
> Could you add an example in `Updated pkg/pdf/example_test.go`?

Yes, I've added an example.

**Comment by xypwn** [comment]
Hi, I'd like this feature too. Why did OP delete their PR repo?

---

BTW, for anyone who needs this feature now, here is the hack I am using in the meantime:
```go
func addUTF8FontFromBytes(family string, style consts.Style, bytes []byte) {
	reflect.ValueOf(m.(*pdf.PdfMaroto).Pdf).MethodByName("AddUTF8FontFromBytes").Call([]reflect.Value{
		reflect.ValueOf(family),
		reflect.ValueOf(string(style)),
		reflect.ValueOf(bytes),
	})
}
```
It ain't pretty, but it gets the job done.

**Comment by thijsheijden** [comment]
Sorry, due to the long wait I assumed it was not wanted. I'll recreate and reopen.

**Comment by thijsheijden** [comment]
Reopened here https://github.com/johnfercher/maroto/pull/255

**Comment by xypwn** [comment]
Awesome :)
This is definitely a wanted and IMO a needed feature, since there is no "official" way to load fonts from memory/static FS, and having this feature allows for fully self-contained executables.

**Pull request closed without merging**
