### PR TITLE
Updated Issue template

### PR DESCRIPTION
**Pull request by soulspark666**
Added Bug report and Feature Request

### CODE REVIEW

**Comment by johnfercher** [comment]
Could you fix this conflict?

**Comment by soulspark666** [comment]
Can you please tell me what is the conflicting with issue_template.md??

**Comment by soulspark666** [comment]
And I don't have write access
conflict

**Comment by johnfercher** [comment]
Hi, you may merge the dev branch from my repository into yours. And then resolve the conflicts.

https://help.github.com/en/articles/merging-an-upstream-repository-into-your-fork

**Comment by soulspark666** [comment]
please approve

**Pull request merged**
